### ISSUE TITLE
Customer column and Symfony services

### ISSUE THREAD

**Issue by Grazulex** [Abhoryo/APYDataGridBundle#673]
Hello,

I have create my own type of column and put the file into my bundle (Xxx/Bundle/AdminBundle/Grid/Column/ThumbColumn.php).
Now I try to load this new type vie the services and but I don't find the good configuration.
Here are my 2 files 

services.yml
```
services:
    grid.column.thumb:
        class: Xxx\Bundle\AdminBundle\Grid\Column\ThumbColumn
        tags:
            -  { name: grid.column.extension }
```

ThumbColumn.php
```
<?php
namespace APY\DataGridBundle\Grid\Column;
class ThumbColumn extends Column
{
    public function getType()
    {
        return 'thumb';
    }
}
```

When I try I have this error 
The autoloader expected class "Xxx\Bundle\AdminBundle\Grid\Column\ThumbColumn" to be defined in file "C:\wamp\www\ecom/src\Xxx\Bundle\AdminBundle\Grid\Column\ThumbColumn.php". The file was found but the class was not in it, the class name or namespace probably has a typo.

Please, can you help me ?
